{
 "title": "Docker Desktop Kubernetes All-in-one",
 "description": "This dashboard is intended to work on local-Docker-Desktop-based Kubernetes- Originally based on  https://github.com/sysnet4admin/_Book_k8sInfra Notice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_node_info,instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},  pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Master Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "label_replace(avg by (kubernetes_node) (time() - node_boot_time_seconds), \"node\", \"$1\", \"kubernetes_node\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node\"}[$duration])) / sum(machine_cpu_cores)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{instance=\"$node\"}[$duration])) / sum(machine_memory_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network Traffic Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes", "label": "Received | Sent" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(in)"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(out)"
    }
   ]
  },
  {
   "title": "API Server Call",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$duration]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  { "title": "Real Time Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[30s])) / sum(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{instance=\"$node\"}[30s])) / sum(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_current{instance=\"$node\"}[30s]))"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (avg_over_time(process_open_fds{instance=\"$node\"}[$duration]))",
     "legendFormat": "Process Opened FD"
    }
   ]
  },
  {
   "title": "Disk IOPS Complete",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{instance=\"$node\"}"
    }
   ]
  },
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Pod Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-kube_pod_start_time{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod Operation Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "Restart within 10 min",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[10m])))"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory(bytes)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=\"$pod\"})",
     "legendFormat": "File system usage"
    }
   ]
  },
  {
   "title": "Resource Allocation Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Traffic Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes", "label": "Received | Sent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Memory Status (Swap/Failure)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{pod=\"$pod\"}) by (pod)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{pod=\"$pod\"}[$duration])) by (pod)",
     "legendFormat": "Memory Failure"
    }
   ]
  },
  {
   "title": "Number Of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_threads{pod=\"$pod\", container!=\"POD\"})",
     "legendFormat": "Thread"
    },
    {}
   ]
  }
 ]
}